<?php

namespace Model {
        
    use Doctrine\ORM\EntityRepository;

    /**
    * UserRepository
    *
    * This class was generated by the Doctrine ORM. Add your own custom
    * repository methods below.
    *
    * @category PHP
    * @package  WebrdFramework
    * @author   Romain Duquesne <romain.duquesne.mail@gmail.com>
    * @license  https://github.com/tuken80/webrd/blob/master/LICENCE MIT License
    * @link     https://github.com/tuken80/webrd.git
    */
    class UserRepository extends EntityRepository
    {
    }
}
